apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-app-deploy
  namespace: default
  labels:
    app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 3
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app-container
        image: b6atalay/welcome-app5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: hello-app-port

      restartPolicy: Always